### ISSUE TITLE
No support for Edifact extensions, i.e. EAN011, available?

### ISSUE THREAD

**Issue by RovoMe** [smooks/smooks-edi-cartridge#55]
I have the use-case where I have to convert a D.01B Invoice which uses EAN011 extensions, i.e. a `IMD+C++CU::9'` segment (https://www.gs1.org/sites/default/files/docs/eancom/ean02s4/part2/invoic/0541.htm), though upon reading in the stream the following exception is raised:

```
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 4889; cvc-enumeration-valid: Value 'CU' is not facet-valid with respect to enumeration '[1, 2, 3, 4, 5]'. It must be a value from the enumeration.
	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at org.apache.xerces.util.ErrorHandlerWrapper.error(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaValidator$XSIErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaValidator.reportSchemaError(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaValidator.elementLocallyValidType(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaValidator.processElementContent(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaValidator.handleEndElement(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaValidator.endElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanEndElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.jaxp.validation.StreamValidatorHelper.validate(Unknown Source)
	at org.apache.xerces.jaxp.validation.ValidatorImpl.validate(Unknown Source)
	at javax.xml.validation.Validator.validate(Validator.java:124)
	at org.apache.daffodil.util.Validator$.validateXMLSources(Validator.scala:87)
	at org.apache.daffodil.processors.ParseResult.validateResult(DataProcessor.scala:682)
	at org.apache.daffodil.processors.DataProcessor.$anonfun$parse$1(DataProcessor.scala:419)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at org.apache.daffodil.ExecutionMode$.$anonfun$usingRuntimeMode$1(ExecutionMode.scala:65)
	at org.apache.daffodil.processors.DataProcessor.parse(DataProcessor.scala:408)
	at org.apache.daffodil.processors.DataProcessor.parse(DataProcessor.scala:404)
	at org.apache.daffodil.japi.DataProcessor.parse(Daffodil.scala:718)
	at org.smooks.cartridges.dfdl.parser.DfdlParser.parse(DfdlParser.java:180)
	... 8 more

Process finished with exit code 1
```

as clearly the validator only uses the default [`IMD` segment definition](https://service.unece.org/trade/untdid/d01b/trsd/trsdimd.htm) which only defines the [5 specified values](https://service.unece.org/trade/untdid/d01b/tred/tred7009.htm) for item description codes mentioned also by the exception message.

Edit: I'm currently using version `2.0.0-M1` of this library

**Comment by claudemamo** [comment]
You can extract the DFDL schemas from the schema pack (i.e., edifact-schemas-2.0.0-M1-d01b.jar) and edit the ItemDescriptionCode type in EDIFACT-Segments.dfdl.xsd to include any additional codes. Assuming the schemaURI is correctly set, the EDIFACT cartridge will parse and unparse with the customised schemas if you place them in your Java classpath.

**Comment by phax** [comment]
What is your experience on the topic of codelists: to our understanding "subsets" like EANCOM can redefine code lists values, so having a set of schemas available without the enum restrictions could be valuable. Would that make sense from your point of view?

**Comment by claudemamo** [comment]
It does. I'll re-open the ticket as a feature request but, as a workaround, you can set _validationMode_ to "Off".

**Comment by phax** [comment]
Yes thank you. My initial thoughts on this one was to provide a second artifact (like `edifact-schemas-nocode`) that basically uses the same templates for creation but just omit the "<enumeration>" values.

I think a separate atifact makes more sense to avoid that the existing one gets bigger.

If this is something you'd be interested in, we'd be happy to provide a PR.

**Comment by claudemamo** [comment]
That's one approach though long-term I'm concerned that we could end up with a "schema hell". We've already had another user [asking separate schema packs to capture the fully qualified names](https://groups.google.com/g/smooks-user/c/_URv2-hffWA) of elements. Perhaps we could parameterize the schema. Parts of the schemas are already parameterized (either through DFDL variables or [Mustache templates](https://github.com/smooks/smooks-edi-cartridge/blob/v2.0.0-M1/common-schemas/src/main/resources/EDIFACT-Common/EDIFACT-Interchange.dfdl.xsd.mustach)) but it might take a fair amount of work to extend the approach.

**Comment by phax** [comment]
Thanks Claude, I share your concerns and eventually that is something that should not be part of the overall project.
Maybe it would be sufficient to extend [EDG](https://github.com/smooks/smooks-edi-cartridge/tree/master/edg) with some parameters to make generation more customizable. Than we can keep our own Schemas but base them on the official ZIP files without duplicating this information for each schema artefact.

Being at the very beginning to understand Smooks, our main focus is the performance, as reading the full set of schemas is quite time consuming. So everything that can be done on build time to speed up the process is welcome (hence the [PR](https://github.com/smooks/smooks-edi-cartridge/pull/57) on disk cache). Of course this is out of scope for this particular issue...

**Comment by claudemamo** [comment]
Sounds good to me.

**Comment by RovoMe** [comment]
We now agreed to use Smooks' `UnEdifactSpecificationReader` to generate the basic validation objects and use a more custom approach to perform Edifact validation on our side. This issue is therefore not of relevance to us further :)
