### ISSUE TITLE
edifact-to-xml example does not run on Windows. tests both on M1 and M2

### ISSUE THREAD

**Issue by jfclavier** [smooks/smooks-edi-cartridge#60]
While testing edifact example, there is an error on building the D03B EDIFACT-Interchange6125501674812409972.dfdl.xsd in temp.
When I look to the file it is not xml valid. (I used xerces validation in notepad++).
The © character is changed to xA9
I guess the problem is in MustacheParser compile method which, I suppose, does not read the file using utf-8.

d:\smooks\smooks-examples\edifact-to-xml>mvn clean install
[INFO] Scanning for projects...
[INFO]
[INFO] --------< org.smooks.examples:smooks-example-unedifact-to-xml >---------
[INFO] Building Smooks Example - UN/EDIFACT - To XML 1.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ smooks-example-unedifact-to-xml ---
[INFO] Deleting d:\smooks\smooks-examples\edifact-to-xml\target
[INFO]
[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforce) @ smooks-example-unedifact-to-xml ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ smooks-example-unedifact-to-xml ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory d:\smooks\smooks-examples\edifact-to-xml\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ smooks-example-unedifact-to-xml ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to d:\smooks\smooks-examples\edifact-to-xml\target\classes
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ smooks-example-unedifact-to-xml ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ smooks-example-unedifact-to-xml ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to d:\smooks\smooks-examples\edifact-to-xml\target\test-classes
[INFO]
[INFO] --- maven-surefire-plugin:2.22.2:test (default-test) @ smooks-example-unedifact-to-xml ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.smooks.examples.edifact2xml.MainTestCase
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.822 s <<< FAILURE! - in org.smooks.examples.edifact2xml.MainTestCase
[ERROR] testRunSmooksTransform  Time elapsed: 1.818 s  <<< ERROR!
org.smooks.cdr.SmooksConfigurationException: Error invoking @PostConstruct method 'initialize' on class 'org.smooks.cartridges.dfdl.parser.DfdlParser'.
        at org.smooks.cdr.lifecycle.phase.AbstractLifecyclePhase.invoke(AbstractLifecyclePhase.java:78)
        at org.smooks.cdr.lifecycle.phase.PostConstructLifecyclePhase.doApplyLifecycle(PostConstructLifecyclePhase.java:88)
        at org.smooks.cdr.lifecycle.phase.AbstractLifecyclePhase.applyLifecycle(AbstractLifecyclePhase.java:60)
        at org.smooks.cdr.lifecycle.DefaultLifecycleManager.applyPhase(DefaultLifecycleManager.java:52)
        at org.smooks.delivery.JavaContentHandlerFactory$1.apply(JavaContentHandlerFactory.java:99)
        at org.smooks.delivery.JavaContentHandlerFactory$1.apply(JavaContentHandlerFactory.java:85)
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
        at org.smooks.delivery.JavaContentHandlerFactory.create(JavaContentHandlerFactory.java:85)
        at org.smooks.delivery.DefaultContentDeliveryConfigBuilder$ContentHandlerExtractionStrategy.addContentDeliveryUnit(DefaultContentDeliveryConfigBuilder.java:520)
        at org.smooks.delivery.DefaultContentDeliveryConfigBuilder$ContentHandlerExtractionStrategy.applyContentDeliveryUnitStrategy(DefaultContentDeliveryConfigBuilder.java:464)
        at org.smooks.delivery.DefaultContentDeliveryConfigBuilder$ContentHandlerExtractionStrategy.applyStrategy(DefaultContentDeliveryConfigBuilder.java:451)
        at org.smooks.delivery.DefaultContentDeliveryConfigBuilder$SmooksResourceConfigurationTableIterator.iterate(DefaultContentDeliveryConfigBuilder.java:602)
        at org.smooks.delivery.DefaultContentDeliveryConfigBuilder$SmooksResourceConfigurationTableIterator.access$300(DefaultContentDeliveryConfigBuilder.java:582)
        at org.smooks.delivery.DefaultContentDeliveryConfigBuilder.extractContentHandlers(DefaultContentDeliveryConfigBuilder.java:393)
        at org.smooks.delivery.DefaultContentDeliveryConfigBuilder.load(DefaultContentDeliveryConfigBuilder.java:255)
        at org.smooks.delivery.DefaultContentDeliveryConfigBuilder.build(DefaultContentDeliveryConfigBuilder.java:138)
        at org.smooks.container.standalone.StandaloneExecutionContext.<init>(StandaloneExecutionContext.java:118)
        at org.smooks.container.standalone.StandaloneExecutionContext.<init>(StandaloneExecutionContext.java:92)
        at org.smooks.Smooks.createExecutionContext(Smooks.java:458)
        at org.smooks.Smooks.createExecutionContext(Smooks.java:416)
        at org.smooks.Smooks.filterSource(Smooks.java:490)
        at org.smooks.examples.edifact2xml.Main.runSmooksTransform(Main.java:77)
        at org.smooks.examples.edifact2xml.MainTestCase.testRunSmooksTransform(MainTestCase.java:59)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:686)
        at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
        at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
        at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
        at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
        at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:212)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:208)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:137)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:71)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
        at java.util.ArrayList.forEach(ArrayList.java:1259)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
        at java.util.ArrayList.forEach(ArrayList.java:1259)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
        at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
        at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:124)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
**Caused by: org.smooks.cdr.SmooksConfigurationException: org.smooks.cdr.SmooksConfigurationException:** java.lang.RuntimeException: Schema Definition Error: Error loading schema due to org.xml.sax.SAXParseException; systemId: file:/C:/Users/JEAN-F~1/AppData/Local/Temp/EDIFACT-Interchange6125501674812409972.dfdl.xsd; lineNumber: 0; columnNumber: 0; java.nio.charset.MalformedInputException: Input length = 1
Schema context: file:/C:/Users/JEAN-F~1/AppData/Local/Temp/EDIFACT-Interchange6125501674812409972.dfdl.xsd Location in file:/C:/Users/JEAN-F~1/AppData/Local/Temp/EDIFACT-Interchange6125501674812409972.dfdl.xsd
        at org.smooks.cartridges.edi.EdiDataProcessorFactory.createDataProcessor(EdiDataProcessorFactory.java:87)
        at org.smooks.cartridges.dfdl.parser.DfdlParser.initialize(DfdlParser.java:175)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.smooks.cdr.lifecycle.phase.AbstractLifecyclePhase.invoke(AbstractLifecyclePhase.java:74)
        ... 87 more
Caused by: org.smooks.cdr.SmooksConfigurationException: java.lang.RuntimeException: Schema Definition Error: Error loading schema due to org.xml.sax.SAXParseException; systemId: file:/C:/Users/JEAN-F~1/AppData/Local/Temp/EDIFACT-Interchange6125501674812409972.dfdl.xsd; lineNumber: 0; columnNumber: 0; java.nio.charset.MalformedInputException: Input length = 1
Schema context: file:/C:/Users/JEAN-F~1/AppData/Local/Temp/EDIFACT-Interchange6125501674812409972.dfdl.xsd Location in file:/C:/Users/JEAN-F~1/AppData/Local/Temp/EDIFACT-Interchange6125501674812409972.dfdl.xsd
        at org.smooks.cartridges.edifact.EdifactDataProcessorFactory.doCreateDataProcessor(EdifactDataProcessorFactory.java:124)
        at org.smooks.cartridges.edi.EdiDataProcessorFactory.createDataProcessor(EdiDataProcessorFactory.java:85)
        ... 93 more
Caused by: java.lang.RuntimeException: Schema Definition Error: Error loading schema due to org.xml.sax.SAXParseException; systemId: file:/C:/Users/JEAN-F~1/AppData/Local/Temp/EDIFACT-Interchange6125501674812409972.dfdl.xsd; lineNumber: 0; columnNumber: 0; java.nio.charset.MalformedInputException: Input length = 1
Schema context: file:/C:/Users/JEAN-F~1/AppData/Local/Temp/EDIFACT-Interchange6125501674812409972.dfdl.xsd Location in file:/C:/Users/JEAN-F~1/AppData/Local/Temp/EDIFACT-Interchange6125501674812409972.dfdl.xsd
        at org.smooks.cartridges.dfdl.DataProcessorFactory.lambda$compileOrGet$0(DataProcessorFactory.java:110)
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
        at org.smooks.cartridges.dfdl.DataProcessorFactory.compileOrGet(DataProcessorFactory.java:105)
        at org.smooks.cartridges.edifact.EdifactDataProcessorFactory.doCreateDataProcessor(EdifactDataProcessorFactory.java:122)
        ... 94 more
Caused by: Schema Definition Error: Error loading schema due to org.xml.sax.SAXParseException; systemId: file:/C:/Users/JEAN-F~1/AppData/Local/Temp/EDIFACT-Interchange6125501674812409972.dfdl.xsd; lineNumber: 0; columnNumber: 0; java.nio.charset.MalformedInputException: Input length = 1
Schema context: file:/C:/Users/JEAN-F~1/AppData/Local/Temp/EDIFACT-Interchange6125501674812409972.dfdl.xsd Location in file:/C:/Users/JEAN-F~1/AppData/Local/Temp/EDIFACT-Interchange6125501674812409972.dfdl.xsd
        at org.apache.daffodil.dsom.DFDLSchemaFile.error(DFDLSchemaFile.scala:103)
        at org.apache.daffodil.dsom.DFDLSchemaFile.fatalError(DFDLSchemaFile.scala:112)
        at org.apache.daffodil.xml.DaffodilConstructingLoader.load(DaffodilConstructingLoader.scala:192)
        at org.apache.daffodil.xml.DaffodilXMLLoader.load(DaffodilXMLLoader.scala:567)
        at org.apache.daffodil.dsom.DFDLSchemaFile.$anonfun$loadedNode$1(DFDLSchemaFile.scala:127)
        at org.apache.daffodil.oolag.OOLAG$OOLAGValueBase.liftedTree1$1(OOLAG.scala:675)
        at org.apache.daffodil.oolag.OOLAG$OOLAGValueBase.valueAsAny$lzycompute(OOLAG.scala:673)
        at org.apache.daffodil.oolag.OOLAG$OOLAGValueBase.valueAsAny(OOLAG.scala:670)
        at org.apache.daffodil.oolag.OOLAG$OOLAGValue.value$lzycompute(OOLAG.scala:720)
        at org.apache.daffodil.oolag.OOLAG$OOLAGValue.value(OOLAG.scala:720)
        at org.apache.daffodil.dsom.DFDLSchemaFile.loadedNode(DFDLSchemaFile.scala:114)
        at org.apache.daffodil.dsom.DFDLSchemaFile.node$lzycompute(DFDLSchemaFile.scala:136)
        at org.apache.daffodil.dsom.DFDLSchemaFile.node(DFDLSchemaFile.scala:136)
        at org.apache.daffodil.dsom.IIBase.$anonfun$iiSchemaFile$1(IIBase.scala:275)
        at org.apache.daffodil.oolag.OOLAG$OOLAGValueBase.liftedTree1$1(OOLAG.scala:675)
        at org.apache.daffodil.oolag.OOLAG$OOLAGValueBase.valueAsAny$lzycompute(OOLAG.scala:673)
        at org.apache.daffodil.oolag.OOLAG$OOLAGValueBase.valueAsAny(OOLAG.scala:670)
        at org.apache.daffodil.oolag.OOLAG$OOLAGValue.value$lzycompute(OOLAG.scala:720)
        at org.apache.daffodil.oolag.OOLAG$OOLAGValue.value(OOLAG.scala:720)
        at org.apache.daffodil.dsom.IIBase.iiSchemaFile(IIBase.scala:273)
        at org.apache.daffodil.dsom.Import.$anonfun$mapPair$3(Import.scala:65)
        at scala.Option.getOrElse(Option.scala:189)
        at org.apache.daffodil.dsom.Import.$anonfun$mapPair$1(Import.scala:45)
        at org.apache.daffodil.oolag.OOLAG$OOLAGValueBase.liftedTree1$1(OOLAG.scala:675)
        at org.apache.daffodil.oolag.OOLAG$OOLAGValueBase.valueAsAny$lzycompute(OOLAG.scala:673)
        at org.apache.daffodil.oolag.OOLAG$OOLAGValueBase.valueAsAny(OOLAG.scala:670)
        at org.apache.daffodil.oolag.OOLAG$OOLAGValue.value$lzycompute(OOLAG.scala:720)
        at org.apache.daffodil.oolag.OOLAG$OOLAGValue.value(OOLAG.scala:720)
        at org.apache.daffodil.dsom.Import.mapPair(Import.scala:43)
        at org.apache.daffodil.dsom.IIBase.$anonfun$notSeenThisBefore$1(IIBase.scala:147)
        at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:23)
        at org.apache.daffodil.oolag.OOLAG$OOLAGValueBase.liftedTree1$1(OOLAG.scala:675)
        at org.apache.daffodil.oolag.OOLAG$OOLAGValueBase.valueAsAny$lzycompute(OOLAG.scala:673)
        at org.apache.daffodil.oolag.OOLAG$OOLAGValueBase.valueAsAny(OOLAG.scala:670)
        at org.apache.daffodil.oolag.OOLAG$OOLAGValue.value$lzycompute(OOLAG.scala:720)
        at org.apache.daffodil.oolag.OOLAG$OOLAGValue.value(OOLAG.scala:720)
        at org.apache.daffodil.dsom.IIBase.notSeenThisBefore(IIBase.scala:146)
        at org.apache.daffodil.dsom.IIBase.$anonfun$iiSchemaFileMaybe$1(IIBase.scala:264)
        at org.apache.daffodil.oolag.OOLAG$OOLAGValueBase.liftedTree1$1(OOLAG.scala:675)
        at org.apache.daffodil.oolag.OOLAG$OOLAGValueBase.valueAsAny$lzycompute(OOLAG.scala:673)
        at org.apache.daffodil.oolag.OOLAG$OOLAGValueBase.valueAsAny(OOLAG.scala:670)
        at org.apache.daffodil.oolag.OOLAG$OOLAGValue.value$lzycompute(OOLAG.scala:720)
        at org.apache.daffodil.oolag.OOLAG$OOLAGValue.value(OOLAG.scala:720)
        at org.apache.daffodil.dsom.IIBase.iiSchemaFileMaybe(IIBase.scala:263)
        at org.apache.daffodil.dsom.IIBase.$anonfun$seenAfter$1(IIBase.scala:172)
        at org.apache.daffodil.oolag.OOLAG$OOLAGValueBase.liftedTree1$1(OOLAG.scala:675)
        at org.apache.daffodil.oolag.OOLAG$OOLAGValueBase.valueAsAny$lzycompute(OOLAG.scala:673)
        at org.apache.daffodil.oolag.OOLAG$OOLAGValueBase.valueAsAny(OOLAG.scala:670)
        at org.apache.daffodil.oolag.OOLAG$OOLAGValue.value$lzycompute(OOLAG.scala:720)
        at org.apache.daffodil.oolag.OOLAG$OOLAGValue.value(OOLAG.scala:720)
        at org.apache.daffodil.dsom.IIBase.seenAfter(IIBase.scala:171)
        at org.apache.daffodil.dsom.SchemaDocIncludesAndImportsMixin.$anonfun$getImportsOrIncludes$1(SchemaDocIncludesAndImportsMixin.scala:147)
        at scala.collection.TraversableOnce$folder$1$.apply(TraversableOnce.scala:187)
        at scala.collection.TraversableOnce$folder$1$.apply(TraversableOnce.scala:185)
        at scala.collection.Iterator.foreach(Iterator.scala:943)
        at scala.collection.Iterator.foreach$(Iterator.scala:943)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
        at scala.collection.IterableLike.foreach(IterableLike.scala:74)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
        at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:189)
        at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:184)
        at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:108)
        at org.apache.daffodil.dsom.SchemaDocIncludesAndImportsMixin.getImportsOrIncludes(SchemaDocIncludesAndImportsMixin.scala:143)
        at org.apache.daffodil.dsom.SchemaDocIncludesAndImportsMixin.getImportsOrIncludes$(SchemaDocIncludesAndImportsMixin.scala:139)
        at org.apache.daffodil.dsom.XMLSchemaDocument.getImportsOrIncludes(SchemaDocument.scala:54)
        at org.apache.daffodil.dsom.SchemaDocIncludesAndImportsMixin.$anonfun$ismli_$1(SchemaDocIncludesAndImportsMixin.scala:158)
        at org.apache.daffodil.oolag.OOLAG$OOLAGValueBase.liftedTree1$1(OOLAG.scala:675)
        at org.apache.daffodil.oolag.OOLAG$OOLAGValueBase.valueAsAny$lzycompute(OOLAG.scala:673)
        at org.apache.daffodil.oolag.OOLAG$OOLAGValueBase.valueAsAny(OOLAG.scala:670)
        at org.apache.daffodil.oolag.OOLAG$OOLAGValue.value$lzycompute(OOLAG.scala:720)
        at org.apache.daffodil.oolag.OOLAG$OOLAGValue.value(OOLAG.scala:720)
        at org.apache.daffodil.dsom.SchemaDocIncludesAndImportsMixin.ismli_(SchemaDocIncludesAndImportsMixin.scala:157)
        at org.apache.daffodil.dsom.SchemaDocIncludesAndImportsMixin.importStatementsMap(SchemaDocIncludesAndImportsMixin.scala:155)
        at org.apache.daffodil.dsom.SchemaDocIncludesAndImportsMixin.importStatementsMap$(SchemaDocIncludesAndImportsMixin.scala:155)
        at org.apache.daffodil.dsom.XMLSchemaDocument.importStatementsMap(SchemaDocument.scala:54)
        at org.apache.daffodil.dsom.SchemaDocIncludesAndImportsMixin.$anonfun$sali_$1(SchemaDocIncludesAndImportsMixin.scala:165)
        at org.apache.daffodil.oolag.OOLAG$OOLAGValueBase.liftedTree1$1(OOLAG.scala:675)
        at org.apache.daffodil.oolag.OOLAG$OOLAGValueBase.valueAsAny$lzycompute(OOLAG.scala:673)
        at org.apache.daffodil.oolag.OOLAG$OOLAGValueBase.valueAsAny(OOLAG.scala:670)
        at org.apache.daffodil.oolag.OOLAG$OOLAGValue.value$lzycompute(OOLAG.scala:720)
        at org.apache.daffodil.oolag.OOLAG$OOLAGValue.value(OOLAG.scala:720)
        at org.apache.daffodil.dsom.SchemaDocIncludesAndImportsMixin.sali_(SchemaDocIncludesAndImportsMixin.scala:164)
        at org.apache.daffodil.dsom.SchemaDocIncludesAndImportsMixin.seenAfter(SchemaDocIncludesAndImportsMixin.scala:162)
        at org.apache.daffodil.dsom.SchemaDocIncludesAndImportsMixin.seenAfter$(SchemaDocIncludesAndImportsMixin.scala:162)
        at org.apache.daffodil.dsom.XMLSchemaDocument.seenAfter(SchemaDocument.scala:54)
        at org.apache.daffodil.dsom.SchemaSetIncludesAndImportsMixin.$anonfun$allSchemaFiles$1(SchemaSetIncludesAndImportsMixins.scala:62)
        at org.apache.daffodil.oolag.OOLAG$OOLAGValueBase.liftedTree1$1(OOLAG.scala:675)
        at org.apache.daffodil.oolag.OOLAG$OOLAGValueBase.valueAsAny$lzycompute(OOLAG.scala:673)
        at org.apache.daffodil.oolag.OOLAG$OOLAGValueBase.valueAsAny(OOLAG.scala:670)
        at org.apache.daffodil.oolag.OOLAG$OOLAGValue.value$lzycompute(OOLAG.scala:720)
        at org.apache.daffodil.oolag.OOLAG$OOLAGValue.value(OOLAG.scala:720)
        at org.apache.daffodil.dsom.SchemaSetIncludesAndImportsMixin.allSchemaFiles(SchemaSetIncludesAndImportsMixins.scala:60)
        at org.apache.daffodil.dsom.SchemaSetIncludesAndImportsMixin.allSchemaFiles$(SchemaSetIncludesAndImportsMixins.scala:60)
        at org.apache.daffodil.dsom.SchemaSet.allSchemaFiles(SchemaSet.scala:66)
        at org.apache.daffodil.dsom.SchemaSet.$anonfun$isValid$2(SchemaSet.scala:142)
        at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:23)
        at org.apache.daffodil.oolag.OOLAG$.keepGoing(OOLAG.scala:60)
        at org.apache.daffodil.dsom.SchemaSet.isValid$lzycompute(SchemaSet.scala:141)
        at org.apache.daffodil.dsom.SchemaSet.isValid(SchemaSet.scala:140)
        at org.apache.daffodil.dsom.SchemaSet.$anonfun$isError$3(SchemaSet.scala:478)
        at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:23)
        at org.apache.daffodil.oolag.OOLAG$.keepGoing(OOLAG.scala:60)
        at org.apache.daffodil.dsom.SchemaSet.$anonfun$isError$1(SchemaSet.scala:477)
        at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:23)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at org.apache.daffodil.ExecutionMode$.$anonfun$usingCompilerMode$1(ExecutionMode.scala:64)
        at org.apache.daffodil.dsom.SchemaSet.isError(SchemaSet.scala:477)
        at org.apache.daffodil.compiler.ProcessorFactory.isError(Compiler.scala:122)
        at org.apache.daffodil.compiler.Compiler.org$apache$daffodil$compiler$Compiler$$compileSourceInternal(Compiler.scala:340)
        at org.apache.daffodil.compiler.Compiler$.org$apache$daffodil$compiler$Compiler$$compileSourceSynchronizer(Compiler.scala:378)
        at org.apache.daffodil.compiler.Compiler.compileSource(Compiler.scala:325)
        at org.apache.daffodil.japi.Compiler.compileSource(Daffodil.scala:176)
        at org.apache.daffodil.japi.Compiler.compileSource(Daffodil.scala:160)
        at org.smooks.cartridges.dfdl.DfdlSchema.compileSource(DfdlSchema.java:128)
        at org.smooks.cartridges.dfdl.DfdlSchema.compile(DfdlSchema.java:116)
        at org.smooks.cartridges.dfdl.DataProcessorFactory.lambda$compileOrGet$0(DataProcessorFactory.java:108)
        ... 97 more

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   MainTestCase.testRunSmooksTransform:59 » SmooksConfiguration Error invoking @P...
[INFO]
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.915 s
[INFO] Finished at: 2020-11-04T10:51:00+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project smooks-example-unedifact-to-xml: There are test failures.
[ERROR]
[ERROR] Please refer to d:\smooks\smooks-examples\edifact-to-xml\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by jfclavier** [comment]
I removed the © characters in org\smooks\cartridges\edi\edi-schemas\2.0.0-M1\edi-schemas-2.0.0-M1.jar EDIFACT-Common\EDIFACT-Interchange.dfdl.xsd.mustache
then test was ok using mvn test.
